module.exports = {
    get_tipo_doc: require("./get_tipo_doc"),
    get_sede: require("./get_sede"),
    get_orientacion: require("./get_orientacion"),
    get_Modulo: require("./get_Modulo"),
    get_user: require("./get_user"),
    get_eps: require("./get_eps"),
    get_genero: require("./get_genero"),
    get_GeneroList: require("./get_GeneroList"),
    get_EpsList: require("./get_EpsList"),
    get_Foto: require("./get_Foto"),
    get_Tipo_Doc_List: require("./get_Tipo_Doc_List"),
    
    create_user: require("./create_user"),
    create_user_account: require("./create_user_account"),

    post_Diagnostico: require("./post_Diagnostico"),
    post_Sede: require("./post_Sede"),
    post_Riesgos: require("./post_Riesgos"),
    post_Alergias: require("./post_Alergias"),
    post_Orientacion: require("./post_Orientacion"),
    post_Genero: require("./post_Genero"),
    post_Eps: require("./post_Eps"),
    post_Foto: require("./post_Foto"),
    post_Medicamento: require("./post_Medicamento"),

    delete_foto: require("./delete_foto"),
    new_Password: require("./new_Password"),
    put_General_Diagnosticos: require("./put_General_Diagnosticos"),
    put_General_Riesgos: require("./put_General_Riesgos"),
    put_General_Medicamento: require("./put_General_Medicamento"),
    put_General_Alergia: require("./put_General_Alergia"),
    put_General_Eps: require("./put_General_Eps"),
    put_General_Genero: require("./put_General_Genero"),
};
